version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    expose:
      - 3306
